
project_id = "ilhzzroafedbyttdfypf"

[auth]
enabled = true
external_oauth_enabled = true
external_oauth_redirect_urls = ["https://ilhzzroafedbyttdfypf.supabase.co/auth/v1/callback"]

[functions.sharing-permissions]
verify_jwt = true

[functions.access-request-response]
verify_jwt = true

[functions.respond-to-appointment-access-request]
verify_jwt = true

[functions.log_anchor]
verify_jwt = true
