
export const appointmentTypes = [
  { value: "Annual Physical", label: "Annual Physical" },
  { value: "Follow-up", label: "Follow-up" },
  { value: "Emergency", label: "Emergency" },
  { value: "Specialist Consultation", label: "Specialist Consultation" },
  { value: "Lab Work", label: "Lab Work" },
  { value: "Vaccination", label: "Vaccination" },
  { value: "Mental Health", label: "Mental Health" },
  { value: "Cardiology", label: "Cardiology" },
  { value: "Telehealth", label: "Telehealth" },
  { value: "Urgent Care", label: "Urgent Care" },
];

export const timeSlots = [
  { value: "8:00 AM", label: "8:00 AM" },
  { value: "8:30 AM", label: "8:30 AM" },
  { value: "9:00 AM", label: "9:00 AM" },
  { value: "9:30 AM", label: "9:30 AM" },
  { value: "10:00 AM", label: "10:00 AM" },
  { value: "10:30 AM", label: "10:30 AM" },
  { value: "11:00 AM", label: "11:00 AM" },
  { value: "11:30 AM", label: "11:30 AM" },
  { value: "12:00 PM", label: "12:00 PM" },
  { value: "12:30 PM", label: "12:30 PM" },
  { value: "1:00 PM", label: "1:00 PM" },
  { value: "1:30 PM", label: "1:30 PM" },
  { value: "2:00 PM", label: "2:00 PM" },
  { value: "2:30 PM", label: "2:30 PM" },
  { value: "3:00 PM", label: "3:00 PM" },
  { value: "3:30 PM", label: "3:30 PM" },
  { value: "4:00 PM", label: "4:00 PM" },
  { value: "4:30 PM", label: "4:30 PM" },
  { value: "5:00 PM", label: "5:00 PM" },
  { value: "5:30 PM", label: "5:30 PM" },
];
