-- Insert sample HIPAA audit log entries for demonstration
INSERT INTO public.enhanced_audit_logs (
    event_type, 
    severity, 
    user_id, 
    session_id, 
    ip_address, 
    user_agent, 
    resource_type, 
    resource_id, 
    phi_accessed, 
    action_performed, 
    details, 
    compliance_flags,
    retention_until
) VALUES 
(
    'phi_access', 
    'warning', 
    (SELECT id FROM auth.users LIMIT 1), 
    'sess_' || gen_random_uuid()::text, 
    '192.168.1.100', 
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36', 
    'medical_record', 
    gen_random_uuid(), 
    true, 
    'Patient medical record viewed', 
    '{"record_type": "lab_results", "patient_name": "John Doe"}',
    '{"hipaa_compliant": true, "requires_audit": true}',
    NOW() + INTERVAL '7 years'
),
(
    'login', 
    'info', 
    (SELECT id FROM auth.users LIMIT 1), 
    'sess_' || gen_random_uuid()::text, 
    '192.168.1.101', 
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36', 
    'user_session', 
    null, 
    false, 
    'User successful login', 
    '{"login_method": "email_password", "mfa_used": false}',
    '{"authentication_event": true}',
    NOW() + INTERVAL '7 years'
),
(
    'phi_update', 
    'error', 
    (SELECT id FROM auth.users LIMIT 1), 
    'sess_' || gen_random_uuid()::text, 
    '192.168.1.102', 
    'Mozilla/5.0 (iPhone; CPU iPhone OS 14_0 like Mac OS X)', 
    'medical_record', 
    gen_random_uuid(), 
    true, 
    'Failed to update patient record - insufficient permissions', 
    '{"error_code": "INSUFFICIENT_PERMISSIONS", "attempted_action": "update_diagnosis"}',
    '{"security_violation": true, "requires_investigation": true}',
    NOW() + INTERVAL '7 years'
),
(
    'system_access', 
    'critical', 
    (SELECT id FROM auth.users LIMIT 1), 
    'sess_' || gen_random_uuid()::text, 
    '10.0.0.50', 
    'curl/7.68.0', 
    'database', 
    gen_random_uuid(), 
    false, 
    'Unauthorized access attempt to admin panel', 
    '{"ip_reputation": "suspicious", "attempt_count": 5}',
    '{"security_alert": true, "requires_immediate_action": true}',
    NOW() + INTERVAL '7 years'
),
(
    'phi_export', 
    'warning', 
    (SELECT id FROM auth.users LIMIT 1), 
    'sess_' || gen_random_uuid()::text, 
    '192.168.1.200', 
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Edge/91.0.864.59', 
    'audit_logs', 
    gen_random_uuid(), 
    true, 
    'HIPAA audit logs exported', 
    '{"export_format": "CSV", "date_range": "30_days", "record_count": 150}',
    '{"data_export": true, "requires_authorization": true}',
    NOW() + INTERVAL '7 years'
);