
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilhzzroafedbyttdfypf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsaHp6cm9hZmVkYnl0dGRmeXBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMjAzMzIsImV4cCI6MjA2Mjg5NjMzMn0.N7JqBYswLPuQAUPbyCPjjK9Ij2dRKMzn6l4fxyLIMKA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    storage: localStorage
  }
});
